name: ricktionary
description: "Ricktionary: Dive into the Rick and Morty universe with detailed character profiles and infinite scrolling."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  cached_network_image: ^3.4.1
  bloc: ^8.1.4
  flutter_bloc: ^8.1.6
  meta: ^1.15.0
  graphql: ^5.2.0-beta.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
